### ISSUE TITLE
SweetAlert Tutorial

### ISSUE THREAD

**Issue by bstanfield** [davidcrosby/pinch#13]
Right after an event is created, have a pop up that provides them with the link (not necessarily clickable), as well as an explanation of what they can do on this page (short), possibly pointing out the top buttons (print, clone, delete, etc.)

**Comment by davidcrosby** [comment]
Should it be every time, or only if it's the first form?

**Comment by davidcrosby** [comment]
I'm thinking it could get annoying.

**Comment by bstanfield** [comment]
Let's keep it every time for now. And see how it feels.

**Comment by bstanfield** [comment]
Better for testing too if we can see it every time

**Comment by davidcrosby** [comment]
Sounds good.
