### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by bstanfield** [davidcrosby/pinch#26]
Signed up for a job, didn't register after hitting "ok". Looked on admin form, no trace of any sign-up occurring. Also, the landing page job counters (ex: balloons: 0/1) aren't populating.

**Comment by bstanfield** [comment]
Figured it out: if the "extra information" box is left blank in the job, thus leaving the box blank when a volunteer signs up for a job, it simply won't populate.

**Comment by davidcrosby** [comment]
Tried this, it didn't happen for me.
