### ISSUE TITLE
SweetAlert Admin Tutorial

### ISSUE THREAD

**Issue by bstanfield** [davidcrosby/pinch#34]
Once a page has been created, admin might be confused by seeing a spot that says "Full Name" and "Email" just like on the normal page. An alert should pop up explaining this, saying that at any time they can sign up a parent or student by typing in their name and email.

**Comment by bstanfield** [comment]
Additionally, when you click on "Sign Someone Up!" as an admin, it shouldn't say "enter your name and email above" but "enter a volunteer's name and email above"

**Comment by davidcrosby** [comment]
It's up. Probably want to spend more time thinking about the english, I just wrote something pretty standard.

**Comment by davidcrosby** [comment]
Whoops meant to close the Admin Tut issue. Will add this piece of text to that sweetAlert.
